// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package log is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Message
	PlainMessage
	ServiceMessage
	CompleteMessage
	Block
	GetServiceLevelResponse
	GetServiceResponse
	GetResponse
	PostRequest
*/
package log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Text      string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PlainMessage struct {
	Message *Message `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PlainMessage) Reset()                    { *m = PlainMessage{} }
func (m *PlainMessage) String() string            { return proto.CompactTextString(m) }
func (*PlainMessage) ProtoMessage()               {}
func (*PlainMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PlainMessage) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type ServiceMessage struct {
	Message *Message `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Level   string   `protobuf:"bytes,2,opt,name=level" json:"level,omitempty"`
}

func (m *ServiceMessage) Reset()                    { *m = ServiceMessage{} }
func (m *ServiceMessage) String() string            { return proto.CompactTextString(m) }
func (*ServiceMessage) ProtoMessage()               {}
func (*ServiceMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceMessage) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ServiceMessage) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type CompleteMessage struct {
	Message *Message `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Level   string   `protobuf:"bytes,2,opt,name=level" json:"level,omitempty"`
	Service string   `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`
}

func (m *CompleteMessage) Reset()                    { *m = CompleteMessage{} }
func (m *CompleteMessage) String() string            { return proto.CompactTextString(m) }
func (*CompleteMessage) ProtoMessage()               {}
func (*CompleteMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CompleteMessage) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *CompleteMessage) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *CompleteMessage) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type Block struct {
	Service   string     `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Level     string     `protobuf:"bytes,2,opt,name=level" json:"level,omitempty"`
	Messages  []*Message `protobuf:"bytes,3,rep,name=messages" json:"messages,omitempty"`
	StartTime int64      `protobuf:"varint,4,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime   int64      `protobuf:"varint,5,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Block) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Block) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Block) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Block) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Block) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type GetServiceLevelResponse struct {
	Messages []*PlainMessage `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *GetServiceLevelResponse) Reset()                    { *m = GetServiceLevelResponse{} }
func (m *GetServiceLevelResponse) String() string            { return proto.CompactTextString(m) }
func (*GetServiceLevelResponse) ProtoMessage()               {}
func (*GetServiceLevelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetServiceLevelResponse) GetMessages() []*PlainMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GetServiceResponse struct {
	Messages []*ServiceMessage `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *GetServiceResponse) Reset()                    { *m = GetServiceResponse{} }
func (m *GetServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*GetServiceResponse) ProtoMessage()               {}
func (*GetServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetServiceResponse) GetMessages() []*ServiceMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GetResponse struct {
	Messages []*CompleteMessage `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetResponse) GetMessages() []*CompleteMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type PostRequest struct {
	Blocks []*Block `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *PostRequest) Reset()                    { *m = PostRequest{} }
func (m *PostRequest) String() string            { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()               {}
func (*PostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PostRequest) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "log.Message")
	proto.RegisterType((*PlainMessage)(nil), "log.PlainMessage")
	proto.RegisterType((*ServiceMessage)(nil), "log.ServiceMessage")
	proto.RegisterType((*CompleteMessage)(nil), "log.CompleteMessage")
	proto.RegisterType((*Block)(nil), "log.Block")
	proto.RegisterType((*GetServiceLevelResponse)(nil), "log.GetServiceLevelResponse")
	proto.RegisterType((*GetServiceResponse)(nil), "log.GetServiceResponse")
	proto.RegisterType((*GetResponse)(nil), "log.GetResponse")
	proto.RegisterType((*PostRequest)(nil), "log.PostRequest")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x69, 0x9b, 0x76, 0x5a, 0x2a, 0xae, 0x05, 0x23, 0x28, 0x94, 0x3d, 0x48, 0x2f,
	0xd6, 0x7f, 0xe0, 0xc5, 0x83, 0xa0, 0x48, 0x3d, 0xa8, 0x94, 0xd5, 0xbb, 0xa4, 0xed, 0x50, 0x82,
	0x9b, 0x6c, 0xec, 0x8e, 0xc5, 0xef, 0xe2, 0x97, 0x95, 0x4c, 0x92, 0x36, 0x35, 0x78, 0x10, 0xbc,
	0x4d, 0xe6, 0xed, 0xfb, 0xbd, 0x61, 0x26, 0xd0, 0x4d, 0x16, 0x86, 0xcc, 0xd4, 0xe8, 0x21, 0x17,
	0xc2, 0xd5, 0x66, 0x2e, 0xaf, 0xc0, 0x7b, 0x44, 0x6b, 0x83, 0x39, 0x0a, 0x01, 0x35, 0xc2, 0x4f,
	0xf2, 0x9d, 0xbe, 0x33, 0x68, 0x29, 0xae, 0xc5, 0x01, 0xb4, 0x28, 0x8c, 0xd0, 0x52, 0x10, 0x25,
	0xfe, 0x56, 0xdf, 0x19, 0xb8, 0x6a, 0xdd, 0x90, 0x97, 0xd0, 0x19, 0xeb, 0x20, 0x8c, 0x0b, 0xc2,
	0x11, 0x78, 0x51, 0x56, 0x32, 0xa4, 0x7d, 0xde, 0x19, 0x6a, 0x33, 0x1f, 0xe6, 0xb2, 0x2a, 0x44,
	0xf9, 0x04, 0xdd, 0x67, 0x5c, 0x2c, 0xc3, 0x29, 0xfe, 0xd1, 0x29, 0x7a, 0x50, 0xd7, 0xb8, 0x44,
	0xcd, 0xb3, 0xb4, 0x54, 0xf6, 0x21, 0x43, 0xd8, 0xbe, 0x35, 0x51, 0xa2, 0x91, 0xfe, 0x07, 0x28,
	0x7c, 0xf0, 0x6c, 0x36, 0xa0, 0xef, 0x72, 0xbf, 0xf8, 0x94, 0x5f, 0x0e, 0xd4, 0x6f, 0xb4, 0x99,
	0xbe, 0x95, 0xdf, 0x38, 0x1b, 0x6f, 0x7e, 0x61, 0x0e, 0xa0, 0x99, 0x87, 0x5a, 0xdf, 0xed, 0xbb,
	0x95, 0x91, 0x56, 0xaa, 0x38, 0x04, 0xb0, 0x14, 0x2c, 0xe8, 0x35, 0xdd, 0xb4, 0x5f, 0xcb, 0xb6,
	0xce, 0x9d, 0x97, 0x30, 0x42, 0xb1, 0x0f, 0x4d, 0x8c, 0x67, 0x99, 0x58, 0x67, 0xd1, 0xc3, 0x78,
	0x96, 0x4a, 0xf2, 0x1e, 0xf6, 0x46, 0x48, 0xf9, 0x6e, 0x1f, 0xd2, 0x58, 0x85, 0x36, 0x31, 0xb1,
	0x45, 0x71, 0x5c, 0x8a, 0x77, 0x38, 0x7e, 0x87, 0xe3, 0xcb, 0x07, 0x5c, 0xcf, 0x20, 0xef, 0x40,
	0xac, 0x49, 0x2b, 0xc8, 0x49, 0x05, 0xb2, 0xcb, 0x90, 0xcd, 0x6b, 0x96, 0x30, 0xd7, 0xd0, 0x1e,
	0x21, 0xad, 0xfc, 0xa7, 0x15, 0x7f, 0x8f, 0xfd, 0x3f, 0xae, 0x57, 0x02, 0x9c, 0x41, 0x7b, 0x6c,
	0x2c, 0x29, 0x7c, 0xff, 0x40, 0x4b, 0x42, 0x42, 0x63, 0x92, 0x6e, 0xbf, 0xb0, 0x03, 0xdb, 0xf9,
	0x20, 0x2a, 0x57, 0x26, 0x0d, 0xfe, 0xbd, 0x2f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x07, 0x7c,
	0x7b, 0x5a, 0xf0, 0x02, 0x00, 0x00,
}
