// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package log is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Message
	Block
	GetResponse
*/
package log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Text      string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Block struct {
	Service   string     `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Level     string     `protobuf:"bytes,2,opt,name=level" json:"level,omitempty"`
	Messages  []*Message `protobuf:"bytes,3,rep,name=messages" json:"messages,omitempty"`
	StartTime int64      `protobuf:"varint,4,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime   int64      `protobuf:"varint,5,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Block) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Block) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Block) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Block) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Block) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type GetResponse struct {
	Messages []*Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "log.Message")
	proto.RegisterType((*Block)(nil), "log.Block")
	proto.RegisterType((*GetResponse)(nil), "log.GetResponse")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0x59, 0xf7, 0x62, 0x2e, 0x73, 0x62, 0x31, 0x58, 0xac, 0xa0, 0x10, 0x52, 0x6d, 0x95,
	0x42, 0x0b, 0x0b, 0x3b, 0x1b, 0x2b, 0x9b, 0xc5, 0x5e, 0x62, 0x6e, 0x08, 0xc1, 0xdd, 0x6c, 0xc8,
	0x0c, 0x87, 0xef, 0xe2, 0xcb, 0xca, 0xed, 0x46, 0xc5, 0xe6, 0xba, 0x99, 0xf9, 0xf8, 0xf9, 0x7e,
	0x06, 0x2e, 0xe7, 0x25, 0x4a, 0xec, 0xa3, 0x6f, 0xd3, 0x80, 0xda, 0xc7, 0xa1, 0x79, 0x84, 0xf2,
	0x85, 0x98, 0xbb, 0x81, 0x10, 0x61, 0x23, 0xf4, 0x29, 0x46, 0xd5, 0xca, 0x56, 0x2e, 0xcd, 0x78,
	0x03, 0x95, 0x8c, 0x81, 0x58, 0xba, 0x30, 0x9b, 0xb3, 0x5a, 0x59, 0xed, 0xfe, 0x0e, 0xcd, 0x97,
	0x82, 0xe2, 0xc9, 0xc7, 0xfe, 0x03, 0x0d, 0x94, 0x4c, 0xcb, 0x61, 0xec, 0x69, 0x8d, 0xff, 0xac,
	0x78, 0x05, 0x85, 0xa7, 0x03, 0xf9, 0x94, 0xae, 0x5c, 0x5e, 0xd0, 0xc2, 0x36, 0x64, 0x2d, 0x1b,
	0x5d, 0x6b, 0xbb, 0xbb, 0xbb, 0x68, 0x7d, 0x1c, 0xda, 0xb5, 0x8b, 0xfb, 0xa5, 0x78, 0x0b, 0xc0,
	0xd2, 0x2d, 0xf2, 0x76, 0xd4, 0x9a, 0x4d, 0xae, 0x90, 0x2e, 0xaf, 0x63, 0x20, 0xbc, 0x86, 0x2d,
	0x4d, 0xfb, 0x0c, 0x8b, 0x04, 0x4b, 0x9a, 0xf6, 0x47, 0xd4, 0x3c, 0xc0, 0xee, 0x99, 0xc4, 0x11,
	0xcf, 0x71, 0x62, 0xfa, 0xa7, 0x54, 0xa7, 0x94, 0xef, 0xe7, 0xe9, 0x3f, 0xf7, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xb3, 0x96, 0x70, 0xbe, 0x31, 0x01, 0x00, 0x00,
}
